Repository vueuse/motion, pull requests merged in 2024-02, with the labels that each got.

#172 chore: add bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: size:M, lgtm

#173 fix: `v-motion` directive variants leaking
  src/directive/index.ts
Labels: size:XS

#174 docs: fix demo reset and code preview
  playgrounds/vite/src/components/CodeBlock.vue
  playgrounds/vite/src/components/DemoBox.vue
Labels: size:S

#176 chore: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size:M, lgtm

#175 fix: types
  package.json
  scripts/fix-nuxt-build.mjs
Labels: size:M

#178 chore: add reproduire actions
  .github/reproduire/needs-reproduction.md
  .github/workflows/reproduire-close.yml
  .github/workflows/reproduire.yml
Labels: size:M, lgtm
